### ISSUE TITLE
Typo in page title - "Raid Guid"

### ISSUE THREAD

**Issue by HHH-GH** [raid-guild/origin-stories#32]
The page title says "Raid Guid"

It should say "Raid Guild"

Easy fix: line 27 of https://github.com/raid-guild/origin-stories/blob/develop/pages/index.js

(Just remembered I noticed this while working on the handbook updates. Hit me up in the Discord if you'd like me to fix it, HHH#4900)

**Comment by thebeyondr** [comment]
Thanks! Good catch... sure, you can fix it just do a PR

**Comment by HHH-GH** [comment]
Done! The PR is into develop; will leave the rest to you :)
